version: '3.8'
services:
  calendar:
    build: calendar
    image: calendar_image
    container_name: calendar_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/workcalendar

  db:
    image: postgres:13.7-alpine
    container_name: calendar-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=workcalendar
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root